### ISSUE TITLE
Date of the entry

### ISSUE THREAD

**Issue by PIC-Nico** [phpbb-de/phpbb-ext-pastebin#12]
The date of an entry should be visible here:
- list of last entrys
- short description of an open entry (for example beside the name of the author)

**Comment by gn36** [comment]
I agree, we should display the date and also the deletion date of the entry (the latter only on the page of the description, not in the list of last entries).

**Comment by PIC-Nico** [comment]
I dont have enough knowledge about this kind of programming but when I take a look at the database, there is no column for the date or for the dates yet, right? So the database has to be expand?!

**Comment by gn36** [comment]
No, the field snippet_time contains the date and time of entry, while the snippet_prune_on contains the date and time after which the entry should be removed. So the information is there, we only need to display it.

**Comment by PIC-Nico** [comment]
Ah okay.. Nice
