### ISSUE TITLE
Issue at date of the entry

### ISSUE THREAD

**Issue by PIC-Nico** [phpbb-de/phpbb-ext-pastebin#19]
The date-information of an entry in the "description area" is not visible if the entry was opend by an guest however it is visible in the "last entrys box".

![noinfoguest](https://cloud.githubusercontent.com/assets/9055317/8778776/011020ea-2f00-11e5-9d9b-71f317e17185.png)

**Comment by PIC-Nico** [comment]
Edit: Only old entrys are affected. When I create a new entry as guest, everything is allright.

**Comment by gn36** [comment]
Ah, I really need to clean up the controller file. I have made this mistake several times now, because the code for display is there twice.

**Comment by Crizz0** [comment]
Fixed via #21
