### ISSUE TITLE
Add "edit" button to the snippets

### ISSUE THREAD

**Issue by Crizz0** [phpbb-de/phpbb-ext-pastebin#31]
At the moment the uploader/owner or the moderators are not able to make edits to the snippets.

This would be usefull, if someone uploads sensitive information like passwords etc. and wants to purge them.

**Comment by JeyP91** [comment]
Hi Christian,
die Möglichkeit Snippets zu editieren würde mich auch sehr interessieren. Hast du schon einen Plan, ob das in nächster Zeit kommt?
Danke dir und viele Grüße

**Comment by Crizz0** [comment]
Mal sehen, ob ich dafür Zeit im Dez/Jan finde.
