### ISSUE TITLE
global here?

### ISSUE THREAD

**Issue by 3D-I** [phpbb-de/phpbb-ext-pastebin#43]
https://github.com/phpbb-de/phpbb-ext-pastebin/blob/c6ebd4be021b2bad51da6cf8ccef2b4207dcd12d/functions/utility.php#L89

May I ask you why the use of global and why has been validated? :smiley_cat:

**Comment by Crizz0** [comment]
Legacy code part. 😉

At the other question, this is the wrong place and person you are asking.
