### ISSUE TITLE
2 Issures with phpBB 3.3.3

### ISSUE THREAD

**Issue by FeelsBadMan1** [phpbb-de/phpbb-ext-pastebin#55]
Hello,
I added Syntaxhighlighting for Python but the Highlighting looks trash somehow. Is there a way to do the exact highlighting that pastebin or hastebin has?
Another Issure is that if i choose the Text as Standard selected option it still have PHP as Standard.
Except these Issures its working fine but i require these.

**Comment by Crizz0** [comment]
Hi,

how did you add the python to the highlighting? Show me your added code. 

How does it look? Screenshot please.

Regards

**Comment by FeelsBadMan1** [comment]
How i added it:

I looked on all files where the highlighting from others is definied and found the correct files. i then added "python," under the text", but i dont remmember the filename. after that it worked but the name was sonething like "python_SYNTAX_HIGLIGHTING" so i looked again and changed it to Python too. here is how it now looks:
![image](https://user-images.githubusercontent.com/40109798/116210018-c59ccd80-a742-11eb-9c16-2d6dd4de9b87.png)

**Comment by FeelsBadMan1** [comment]
also what i found is, that if i switch from darktheme to whitetheme then some parts are still shown in the dartheme such things like last enteties etc.:
![image](https://user-images.githubusercontent.com/40109798/116212729-6f7d5980-a745-11eb-9884-172979d56a51.png)

**Comment by Crizz0** [comment]
Well, this all looks like a incompatibility with your style, which i cannot fix from my side.

**Comment by FeelsBadMan1** [comment]
hmm but with other extentions i not had this problem. I think the issure is not the Theme but the Extention instead.  It would be great if there is a fixed version or another ppastebin that also loks good with the Theme. The Theme im using is "Milk V2" what i bought on themeforest.

**Comment by Crizz0** [comment]
Just copy the "styles/prosilver" directory, rename "prosilver-copy" to the name of your style "milk-something" and make the changes you need in there.

**Comment by FeelsBadMan1** [comment]
Well i think the issure with the Theme that a few Parts will me shown in Dartheme if White theme is selected is probalby a issure from the Theme i alredy asked the Themeauthor for a response about it. However what i noticed is, that on the Syntaxhighlighting from Python a few words are written in black so its difficult to see them on the Dark Theme.
It would be nice if there is any file or option where i can change the color using the colorcode of attributes to make a custom highlighting.

**Comment by Crizz0** [comment]
Yes, would be nice. But it is out of scope of this extension and I won't invest the time for this at the moment.
