### ISSUE TITLE
Mobilstyle Anpassung fehlt

### ISSUE THREAD

**Issue by gn36** [phpbb-de/phpbb-ext-pastebin#7]
Derzeit ist die Darstellung nicht für Mobilgeräte angepasst, d.h. bei geringer Seitenbreite wird die Seitenspalte nicht ausgeblendet. Idealerweise würde der gesamte Style so umgebaut, dass das Menü oben drüber landet oder so.

**Comment by PIC-Nico** [comment]
Hier mal ein Designvorschlag (so sieht das Pastebin-Modul bei mir aus): http://pic-projekte.de/phpBB3/app.php/pastebin/

Das Design ist responsive!

**Comment by gn36** [comment]
Gefällt mir gut. Hast du Lust einen Pull Request zu erstellen so dass wir das direkt mit in die Extension einbinden können?

**Comment by PIC-Nico** [comment]
Ich habe bald Semesterferien, dann kann ich mich damit auseinandersetzen (habe keine Ahnung wie sowas funktioniert). Aber ich habe ja noch deine Links aus dem Forum zu dem Thema. Generell würde ich gerne etwas beitragen... Wie gesagt in den Semesterferien (ab Mitte Juli) geht es dann los.

**Comment by gn36** [comment]
Ok gerne.

**Comment by Crizz0** [comment]
#13

**Comment by PIC-Nico** [comment]
Ich denke dieser "Issue" kann dann wohl geschlossen werden?

**Comment by gn36** [comment]
Yepp, so sieht's aus. Das lässt sich übrigens automatisch kombinieren, indem man beim Kommentar zum Pull Request ein "Fixes #<nummer des issues>" einträgt.
